# Generated by Django 4.0.5 on 2022-06-12 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('written_date', models.DateField()),
                ('board_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.board')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'articles',
            },
        ),
    ]
