# Generated by Django 4.0.5 on 2022-06-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('boardName', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('createDate', models.DateField()),
            ],
            options={
                'db_table': 'boards',
            },
        ),
    ]
