# Generated by Django 4.0.5 on 2022-06-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.AutoField(primary_key=True, serialize=False)),
                ('board_name', models.CharField(max_length=10)),
                ('create_date', models.DateField()),
            ],
            options={
                'db_table': 'boards',
            },
        ),
    ]
